version: '3.1'

services:
  postgres:
    container_name: hrf_universe_postgres
    image: postgres:13.4
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_DB: home_task
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm1n_password
    ports:
      - 5432:5432

  api:
    container_name: hrf_universe_api
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:adm1n_password@postgres/home_task
    ports:
      - 8000:8000
    depends_on:
      - postgres
