"""added statistic table

Revision ID: 2632678c2627
Revises: 991ecb2bf269
Create Date: 2025-05-16 20:35:56.784656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2632678c2627'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire_statistics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('average_days_to_hire', sa.Float(), nullable=False),
    sa.Column('min_days_to_hire', sa.Float(), nullable=False),
    sa.Column('max_days_to_hire', sa.Float(), nullable=False),
    sa.Column('num_postings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire_statistics', schema='public')
    # ### end Alembic commands ###
